#server:
#  servlet-path: /xgg-user-customer
#  port: 32101
#
#dubbo:
#  application:
#    name: xgg-user-cusyomer
#  registry:
#    address: zookeeper://127.0.0.1:2181
#  protocol:
#    name: dubbo
#    port: 20882

apollo:
  #docker 部署不能使用127.0.0.1 因为每个docker容器都有自己的IP地址，也就是各个容器与宿主机形成一个内网，容器们挂在宿主机下。
  #因此127.0.0.1定位的是容器自己。
  meta: http://172.18.92.27:8080
  #meta: http://127.0.0.1:8080
  bootstrap:
    enabled: true